# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setting_window(object):
    def setupUi(self, Setting_window):
        Setting_window.setObjectName("Setting_window")
        Setting_window.resize(267, 142)
        self.button_confirm = QtWidgets.QPushButton(Setting_window)
        self.button_confirm.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.button_confirm.setObjectName("button_confirm")
        self.verticalLayoutWidget = QtWidgets.QWidget(Setting_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 117, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.radioButton_line_0 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_line_0.setChecked(True)
        self.radioButton_line_0.setObjectName("radioButton_line_0")
        self.verticalLayout.addWidget(self.radioButton_line_0)
        self.radioButton_line_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_line_1.setObjectName("radioButton_line_1")
        self.verticalLayout.addWidget(self.radioButton_line_1)
        self.radioButton_line_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_line_2.setObjectName("radioButton_line_2")
        self.verticalLayout.addWidget(self.radioButton_line_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Setting_window)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 10, 121, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.radioButton_qn_0 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_qn_0.setChecked(True)
        self.radioButton_qn_0.setObjectName("radioButton_qn_0")
        self.verticalLayout_2.addWidget(self.radioButton_qn_0)
        self.radioButton_qn_1 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_qn_1.setObjectName("radioButton_qn_1")
        self.verticalLayout_2.addWidget(self.radioButton_qn_1)
        self.radioButton_qn_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_qn_2.setObjectName("radioButton_qn_2")
        self.verticalLayout_2.addWidget(self.radioButton_qn_2)

        self.retranslateUi(Setting_window)
        QtCore.QMetaObject.connectSlotsByName(Setting_window)

    def retranslateUi(self, Setting_window):
        _translate = QtCore.QCoreApplication.translate
        Setting_window.setWindowTitle(_translate("Setting_window", "设置"))
        self.button_confirm.setText(_translate("Setting_window", "确认"))
        self.label_2.setText(_translate("Setting_window", "线路"))
        self.radioButton_line_0.setText(_translate("Setting_window", "主线路"))
        self.radioButton_line_1.setText(_translate("Setting_window", "备线1"))
        self.radioButton_line_2.setText(_translate("Setting_window", "备线2"))
        self.label.setText(_translate("Setting_window", "画质"))
        self.radioButton_qn_0.setText(_translate("Setting_window", "默认"))
        self.radioButton_qn_1.setText(_translate("Setting_window", "最佳"))
        self.radioButton_qn_2.setText(_translate("Setting_window", "一般"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setting_window = QtWidgets.QDialog()
    ui = Ui_Setting_window()
    ui.setupUi(Setting_window)
    Setting_window.show()
    sys.exit(app.exec_())
